

export const ActionType = {
  CREATE_TASK_COLLISION: 'CREATE_TASK_COLLISION',
  DELETE_TASK: 'DELETE_TASK',
  COMPLETE_TASK: 'COMPLETE_TASK',
  CREATE_TASKS: 'CREATE_TASKS',
  TBOS_POP_ROOT: 'TBOS_POP_ROOT',
  TBOS_ADD_ROOT: 'TBOS_ADD_ROOT',
  TOGGLE_TRAIL: 'TOGGLE_TRAIL',
  GET_TASKS: 'GET_TASKS'
}
