

export const ActionType = {
  CREATE_TASK_COLLISION: 'CREATE_TASK_COLLISION',
  DELETE_TASK: 'DELETE_TASK',
  COMPLETE_TASK: 'COMPLETE_TASK',
  CREATE_TASKS: 'CREATE_TASKS',
  CATEGORIZE_TASK: 'CATEGORIZE_TASK',
  TBOS_POP_ROOT: 'TBOS_POP_ROOT',
  TBOS_ADD_ROOT: 'TBOS_ADD_ROOT',
  TOGGLE_TRAIL: 'TOGGLE_TRAIL',
  DRAG_TASK: 'DRAG_TASK',
  TBOS_POP_ROOT_UNTIL: 'TBOS_POP_ROOT_UNTIL',
  GET_TASKS: 'GET_TASKS'
}
